spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}

  jpa:
    hibernate:
      # 개발 단계에서만 이용(create-drop)
      ddl-auto: update
      # ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false # REST용 Framework이므로 OSIV 해제
  
  # swagger 매칭
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # TODO: 개발 마무리시 spring.jpa.open-in-view 세팅 고려(성능 이슈)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO.CLIENT_ID}
            client-secret: ${KAKAO.CLIENT_SECRET}
            redirect-uri: ${BASE.URL}${KAKAO.REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
#              - account_email
          naver:
            client-id: ${NAVER.CLIENT_ID}
            client-secret: ${NAVER.CLIENT_SECRET}
            redirect-uri: ${BASE.URL}${NAVER.REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - name
#              - email
          google:
            client-id: ${GOOGLE.CLIENT_ID}
            client-secret: ${GOOGLE.CLIENT_SECRET}
            redirect-uri: ${BASE.URL}${GOOGLE.REDIRECT_URI}
            scope:
              - profile
#              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# app
app:
  auth:
    token:
      # sh -> openssl rand -hex 64
      secret-key: ${JWT.SECRET_KEY}
      refresh-cookie-key: refresh
  oauth2:
    authorizedRedirectUri: ${BASE.CLIENT_URL}/oauth2/redirect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace